project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!materials/workshop/"

lang: ko

website:
  title: "챗GPT 교육"
  favicon: "images/profile.png"
  google-analytics: "UA-229551680-1"  
  site-url: https://quartopub.com/sites/statkclee/quarto-ds
  page-footer:
    center: |
      [한국 R 사용자회](mailto:admin@r2bit.com)
    left: |
      [Quarto](https://quarto.org/) 개발
    right: |
      [Github 코드 저장소](https://github.com/bit2r/gpt-edu)
    background: "#2780e3"
  sidebar: 
    style: floating
    contents: 
      - href: prerequisite.qmd
        text: "사전 준비"
      - href: timer.qmd
        text: "실습시간"
      - section: "경기도 지식(GSeek):"        
        contents:
          - href: gseek_20230530.qmd
            text: "챗GPT 디지털 글쓰기(5/30)"
          - href: gseek_20230530_write.qmd
            text: "챗GPT 글쓰기 콘텐츠(글감)"
          - href: gseek_20230530_format.qmd
            text: "챗GPT 구조와 외양"
          - href: gseek_20230530_deploy.qmd
            text: "챗GPT 배포와 공유"
      - href: gg_hr_20230515.qmd
        text: "경기도 직무교육(5/15)"
      - section: "경기도청"
        contents:
          - href: gg_20230426.qmd
            text: "직무교육(4/26~28)"        
          - href: gg_20230426_write.qmd
            text: "직무교육 - 글쓰기"            
          - href: gg_20230426_draw.qmd
            text: "직무교육 - 그리기"
          - href: gg_20230426_excel.qmd
            text: "직무교육 - 엑셀"            
      - section: "광명시"
        contents:
          - href: km_20230407.qmd
            text: "직무교육(4/7)"
          - href: km_20230421.qmd
            text: "직무교육(4/21)"
          - href: km_20230407_adv.qmd
            text: "직무교육 심화"            

bibliography: bibliography.bib
csl: apa-single-spaced.csl

format:
  html:
    theme: 
      - litera
      - css/quarto.scss
    toc: true
    
execute:
  freeze: true